# Generated by Django 5.2 on 2025-07-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, to='api.lesson'),
        ),
    ]
